trigger:
- none

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Set Python version $(python.version)'

- script: python -m pip install --upgrade pip
  displayName: 'Update PIP'

- script: |
    cd $(System.DefaultWorkingDirectory)
    git clone https://github.com/nccgroup/ScoutSuite
    cd ScoutSuite
    pip install -r requirements.txt
    python scout.py azure --cli
    tail -1 scoutsuite-report/scoutsuite-results/scoutsuite_results_azure-tenant-*.js | python3 -mjson.tool 
  displayName: 'Run ScoutSuite'

