trigger:
- none

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Set Python version $(python.version)'

- script: python -m pip install --upgrade pip
  displayName: 'Update PIP'

- script: |
    cd $(System.DefaultWorkingDirectory)
    git clone https://github.com/nccgroup/ScoutSuite
    cd ScoutSuite
    pip install -r requirements.txt
    az login -u $(u) -p $(p)
    python scout.py azure --cli
  displayName: 'Run ScoutSuite'

# Copy results to storage
#- task: AzureCLI@1
#  displayName: Az CLI Copy to Storage
#  inputs:
#    azureSubscription: $(azureSubscription)
#    scriptLocation: inlineScript
#    inlineScript: |
#      az storage blob upload-batch \
#        --destination \$web \
#        --account-name "$(storageAccountName)" \
#        --source "$(Agent.BuildDirectory)/$(outputDir)"

# process scoutsuite-report/scoutsuite-results/scoutsuite_results_azure-tenant-*.js | python3 -mjson.tool
- script: |
    pip install -r requirements.txt
    python findInJsonPath.py $(System.DefaultWorkingDirectory)/ScoutSuite/scoutsuite-report/scoutsuite-results/scoutsuite_results_azure-tenant-*.js 'services.*.findings' 

# raise slack alert summary


